### ISSUE TITLE
Emokymai:  vidutine→ vidutinė (rašybos klaida)

### ISSUE THREAD

**Issue by ievajuozapaityte** [mokymai/taisymai--BS-2019#103]
1. **Glaustai aprašykite netikslumą:**  .
2. **Vieta:**   ...
3. **Nukopijuokite visą sakinį su netikslumu:**  Kokiomis aplinkybėmis politiko pažadas „visi gaus ne mažesnes nei vidutine algas“ bus teisingas?
 ...
4. **Netikslumo tekstas:**  vidutine
5. **Siūlomas taisymo tekstas:**  vidutinė
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![53155090_368766213716897_7654130547563692032_n](https://user-images.githubusercontent.com/43252509/53695119-3c86e780-3dc0-11e9-978f-4f7471c18e3a.jpg)

**Comment by GegznaV** [comment]
Emokymai sistemoje jau buvo ištaisyta. 
Coses #104
