### ISSUE TITLE
Svetainė: kokybiniai diskretieji → kaip kokybiniai gali būti diskretūs? 

### ISSUE THREAD

**Issue by giedremikutaite** [mokymai/taisymai--BS-2019#111]
<!-- 
1. Vietoje kokybiniai diskretieji turėt būti kokybiniai nominalieji arba ranginiai, arba kiekybiniai diskretieji.
2.     8.1.2  skyrius, grafikai (teorija), virš video apie histogramas.
3.  " Šie grafikai tinkami kiekybiniams tolydiesiems ir kokybiniams diskretiesiems duomenims."
4.
5. Nežinau kaip taisyti, nes nebesuprantu kuo skiriasi histograma nuo stulpelinės diagramos, ar galima nominaliesiems ir ranginiems naudoti stulpelinę arba histogramą, ar tik stulpelinę diagramą. Ačiū už patikslinimą.
6. 
![image](https://user-images.githubusercontent.com/47522731/53735446-88549200-3e8f-11e9-85c1-b76397bb067d.png)

**Comment by giedremikutaite** [comment]
Kažkodėl neįsikėlė aprašymas.

8.1.2 skyriuje yra sakinys: "Šie grafikai tinkami kiekybiniams tolydiesiems ir kokybiniams diskretiesiems duomenims."

Kaip kokybiniai gali būti diskretieji?

Nebesuprantu kuo skiriasi histograma nuo stulpelinės diagramos. 
1. Ar galima kokybiniems nominaliesiems ir ranginiems naudoti stulpelinę arba histogramą? ar tik stulpelinę?
2. Ar galima kiekybiniems diskretiesiems ir tolydiesiems (jų dažniams atvaizduoti) naudoti histogramą arba stulpelinę? ar tik histogramą?

Dėkoju.

![image](https://user-images.githubusercontent.com/47522731/53735607-0b75e800-3e90-11e9-9a98-83d70534caec.png)

**Comment by GegznaV** [comment]
"kokybiniams diskretiesiems" - čia klaida, turi būti "kiekybiniai".

"Kaip kokybiniai gali būti diskretieji?" Kokybiniai automatiškai yra diskretūs, nes nėra tarpinių reikšmių. Diskretus ~ atskiras.

"Ar galima kokybiniems nominaliesiems ir ranginiems naudoti stulpelinę arba histogramą? ar tik stulpelinę?" Tik stulpelinę, nes reikšmės nėra grupuojamos į intervalus.

"Ar galima kiekybiniems diskretiesiems ir tolydiesiems (jų dažniams atvaizduoti) naudoti histogramą arba stulpelinę? ar tik histogramą?" Jei dydžiai skaitiniai ir jų reikšmes galima grupuoti į intervalus, tada galima naudoti histogramą. Tad tolydiesiems galima tik histogramą, kiekybiniams diskretiesiems - ir stulpelinę (jei reikšmių mažai) ir histogramą.

**Comment by giedremikutaite** [comment]
Dabar man aišku! ačiū už Jūsų laiką.
