### ISSUE TITLE
Svetainė: grįskite → pagrįskite (neteisingai vartojamas žodis)

### ISSUE THREAD

**Issue by ievajuozapaityte** [mokymai/taisymai--BS-2019#118]
1. **Glaustai aprašykite netikslumą:**  netinkamai vartojamas žodis
2. **Vieta:**   .https://mokymai.github.io/biostatistika-2019/aprasomoji-nadojant-Rcmdr.html
3. **Nukopijuokite visą sakinį su netikslumu:**  Atsakymą grįskite duomenų lentelės aprašyme (dokumentacijoje) pateikta informacija bei funkcijos glimpse() rezultatais.
 ...
4. **Netikslumo tekstas:**  grįskite
5. **Siūlomas taisymo tekstas:**  pagrįskite
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![53192383_331304217493904_3115907775775899648_n](https://user-images.githubusercontent.com/43252509/53750723-3e7da300-3eb3-11e9-96e8-13f0306ee3a4.jpg)

**Comment by GegznaV** [comment]
Reikia pagrindimo arba platesnio paaiškinimo, kodėl šis žodis netinkamas"

**Comment by ievajuozapaityte** [comment]
Šiame sakinio kontekste labiau vartotinas žodis pagrįsti.
Žodžių reikšmės:
grįsti - kloti, tiesti lentomis ar rąsteliais aslą, tiltą, kelią;
pagrįsti -  duoti pagrindą, paremti, pagrįsti teiginį.

**Comment by GegznaV** [comment]
Antroji reikšmė: https://www.tv3.lt/zodynas/terminu-zodynas/G/gristi
