### ISSUE TITLE
Skaidrės: imčių sudarymas: ne visiškai → nevisiškai (rašybos klaida)

### ISSUE THREAD

**Issue by ManteRakauskaite** [mokymai/taisymai--BS-2019#120]
1. **Glaustai aprašykite netikslumą:**  rašybos klaida
2. **Vieta:**   Imčių sudarymas, 21 skaidrė.
3. **Nukopijuokite visą sakinį su netikslumu:** 
 „Aklas“ ėmimas (pvz., paimti užsimerkus) iš tikrųjų gali būti ne visiškai atsitiktinis:
4. **Netikslumo tekstas:**  ne visiškai
5. **Siūlomas taisymo tekstas:**  nevisiškai
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/47366086/53754230-fdd65780-3ebb-11e9-8f00-6ec4f1d8a5da.png)
![image](https://user-images.githubusercontent.com/47366086/53754243-07f85600-3ebc-11e9-9cbd-06090a3bce6e.png)

**Comment by GegznaV** [comment]
http://www.vlkk.lt/konsultacijos/5929-nevisiskas-nevisiskai-ne-visai
