### ISSUE TITLE
Skaidrės: imčių sudarymas: steėjimo → stebėjimo (rašybos klaida)

### ISSUE THREAD

**Issue by ManteRakauskaite** [mokymai/taisymai--BS-2019#123]
1. **Glaustai aprašykite netikslumą:**  rašybos klaida
2. **Vieta:**   imčių sudarymas, 41 skaidrė.
3. **Nukopijuokite visą sakinį su netikslumu:** 
 dažna klaida–iš steėjimo eksperimentų daromos priežastinės išvados:
4. **Netikslumo tekstas:**  steėjimo
5. **Siūlomas taisymo tekstas:**  stebėjimo
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/47366086/53755640-b18d1680-3ebf-11e9-8657-067ec034391d.png)

**Comment by GegznaV** [comment]
žr. #106
