### ISSUE TITLE
Svetainė: skyrybos klaida - nereikalingi kableliai

### ISSUE THREAD

**Issue by Karolina10** [mokymai/taisymai--BS-2019#156]
1. **Glaustai aprašykite netikslumą:**  skyrybos klaida - nereikalingi kableliai
2. **Vieta:** 14.5.1 Duomenų nuskaitymas naudojant RStudio
3. **Nukopijuokite visą sakinį su netikslumu:** Tačiau kiekvieną kartą įsitikinkite, ar tikrai stulpeliai turi teisingus pavadinimus (juos vaizduoja pirmoji, pajuodinta, eilutė lange „Data Frame“) ir kiekvienas stulpelis nuskaitomas kaip atskiras stulpelis.
4. **Netikslumo tekstas:**  ...pirmoji, pajuodinta, eilutė
5. **Siūlomas taisymo tekstas:**  ...pirmoji pajuodinta eilutė
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaida10](https://user-images.githubusercontent.com/47525769/57178893-2826a000-6e80-11e9-98be-263922815e3a.png)

**Comment by GegznaV** [comment]
Man rodos, tai yra aiškinamoji aplinkybė. Galbūt kita taisyklė, bet kablelių reikia iš abiejų pusių. Be kablelių išsikreiptų prasmė.
