### ISSUE TITLE
Svetainė: šiame skyriuje -> šio skyriaus

### ISSUE THREAD

**Issue by Egle10** [mokymai/taisymai--BS-2019#168]
1. **Glaustai aprašykite netikslumą:** stiliaus klaida sakinyje
2. **Vieta:**   19. ANOVA ir jos analogai
3. **Nukopijuokite visą sakinį su netikslumu:** Šiame skyriuje metu mokysimės taikyti tik vienfaktorės ANOVA modelį, skirtą nepriklausomoms duomenų imtims, bei šio modelio analogus, kai pažeidžiamos klasikinio vienfaktorės ANOVA modelio prielaidos (pvz., normalumas ar dispersijų homogeniškumas).
4. **Netikslumo tekstas:**  šiame skyriuje
5. **Siūlomas taisymo tekstas:**  šio skyriaus
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaidele2](https://user-images.githubusercontent.com/47539243/57461160-2d6c5c00-727f-11e9-8f02-65f47a16ba2f.png)

**Comment by GegznaV** [comment]
Nereikia žodžio "metu".
