### ISSUE TITLE
Svetainė: skyrybos klaida - nereikalingas kablelis

### ISSUE THREAD

**Issue by Egle10** [mokymai/taisymai--BS-2019#171]
1. **Glaustai aprašykite netikslumą:**  nereikalingas kablelis prieš nei*
2. **Vieta:** 17.3.2 F kriterijus dviejų imčių dispersijoms lyginti
3. **Nukopijuokite visą sakinį su netikslumu:** jei duomenys bus ne normalieji, tai kriterijus labiau vertins nuokrypį nuo normalumo, jei nuokrypį nuo lygių dispersijų.
4. **Netikslumo tekstas:**  normalumo, nei*
5. **Siūlomas taisymo tekstas:** normalumo nei*
* jei -> nei ištaisyta anksčiau
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaidele3](https://user-images.githubusercontent.com/47539243/57462705-0a8f7700-7282-11e9-84fb-acdcfc328841.png)

**Comment by GegznaV** [comment]
Susiję su #170, todėl +0
