### ISSUE TITLE
Skaidrės: Nebūtina atsižvelgti į nei į 𝒑 → Nebūtina atsižvelgti nei į 𝒑  (nereikalingas žodis)

### ISSUE THREAD

**Issue by Dirvelyte** [mokymai/taisymai--BS-2019#177]
1. **Glaustai aprašykite netikslumą:**  nereikalingas žodis "į"
2. **Vieta:** BS-2019--P10-3--pi-skaiciavimas--(v0.1)
3. **Nukopijuokite visą sakinį su netikslumu:** Nebūtina atsižvelgti į nei į 𝒑, nei į n reikšmes.

4. **Netikslumo tekstas:** Nebūtina atsižvelgti į nei į 𝒑, 
5. **Siūlomas taisymo tekstas:** Nebūtina atsižvelgti nei į 𝒑, 
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/47331813/57567654-4abb3a80-73e5-11e9-9a37-c9ec43f689e5.png)

**Comment by GegznaV** [comment]
Atnaujinau skaidres ir paskritai ištryniau tą žalią dėžutę.
