### ISSUE TITLE
Emokymai: Koks turi būti studentų skaičius, kad išmatavus cholesterino kiekį kraujyje vidurkio 99% pasikliautinojo intervalo plotis būtų lygus → Koks turi būti studentų skaičius, kad išmatavus cholesterino kiekį kraujyje, vidurkio 99% pasikliautinojo intervalo plotis būtų lygus (praleistas kablelis)

### ISSUE THREAD

**Issue by ievajuozapaityte** [mokymai/taisymai--BS-2019#183]
1. **Glaustai aprašykite netikslumą:**  praleistas skyrybos ženklas (kablelis). Šiuo atveju šalutinis sakinys, prasidedantis žodžiu ,,kad", turi būti atskirtas kableliu iš abiejų pusių.
2. **Vieta:**  Įskaitinis darbas „Pasikliautiniieji intervalai“
3. **Nukopijuokite visą sakinį su netikslumu:** 
 Koks turi būti studentų skaičius, kad išmatavus cholesterino kiekį kraujyje vidurkio 99% pasikliautinojo intervalo plotis būtų lygus 
4. **Netikslumo tekstas:**  Koks turi būti studentų skaičius, kad išmatavus cholesterino kiekį kraujyje vidurkio 99% pasikliautinojo intervalo plotis būtų lygus 
5. **Siūlomas taisymo tekstas:**  Koks turi būti studentų skaičius, kad išmatavus cholesterino kiekį kraujyje, vidurkio 99% pasikliautinojo intervalo plotis būtų lygus 
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![60592873_353893171928685_3946508541916872704_n](https://user-images.githubusercontent.com/43252509/57706647-d85d8b00-766e-11e9-9f73-c6e81f8d8013.jpg)

**Comment by GegznaV** [comment]
Jei ką reiktų išskirti kableliais iš abiejų pusių, tai dalį "išmatavus cholesterino kiekį kraujyje", bet šioje vietoje skytyba nėra privaloma.
