### ISSUE TITLE
skyrybos klaida - neteisingai panaudotas kablelis po žodžiu "mažiau"

### ISSUE THREAD

**Issue by IndreSab** [mokymai/taisymai--BS-2019#30]
1. **Glaustai aprašykite netikslumą:** skyrybos klaida - neteisingai panaudotas kablelis po žodžiu "mažiau"
2. **Vieta:** BS-2019-P01-3--pradines-savokos_v1.1.pdf 43 skaidrė
3. **Nukopijuokite visą sakinį su netikslumu:**  Jei turi mažai skirtingų reikšmių (pvz., mažiau, kaip 5), tai dažniausiai belieka į jį žiūrėti, kaip į nominalųjį: 
4. **Netikslumo tekstas:** (pvz., mažiau, kaip 5
5. **Siūlomas taisymo tekstas:** mažiau kaip 5
6. **Ekrano nuotrauka („Screenshots“)** 

<img width="874" alt="screenshot 2019-02-08 at 22 11 16" src="https://user-images.githubusercontent.com/47398093/52503547-93006c00-2bee-11e9-9fe5-16b1743db792.png">

**Comment by GegznaV** [comment]
Klaida pradiniame šaltinyje.
