### ISSUE TITLE
Netinkamas terminas "tinklapis"

### ISSUE THREAD

**Issue by JusteNav** [mokymai/taisymai--BS-2019#33]
1. **Glaustai aprašykite netikslumą:** VLKK sako, kad informatikų pasirinktas terminas yra "tinklalapis", o ne "tinklapis". Šaltinis čia: http://www.vlkk.lt/konsultacijos/3502-web-page-tinklalapis-tinklapis
2. **Vieta:** https://mokymai.github.io/biostatistika-2019/index.html pirmas klaidos pasikartojimas, tačiau kadangi šis terminas skaidrėse ir pačiame tinklalapyje vartojamas dažnai, atvejų yra ir daugiau. 
3. **Nukopijuokite visą sakinį su netikslumu:**
Kurso tinklapis
4. **Netikslumo tekstas:** "tinklapis"
5. **Siūlomas taisymo tekstas:** "tinklalapis"
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![image](https://user-images.githubusercontent.com/44645701/52524057-488bf780-2ca1-11e9-858a-aa27b2f3c5ce.png)

**Comment by GegznaV** [comment]
"Pirmiausia pasakytina, kad darybos požiūriu abu žodžiai tinklapis ir tinklalapis yra visiškai taisyklingi."

**Comment by GegznaV** [comment]
Šitoje vietoje, matyt, būtų tinkamas tikslesnis terminas – svetainė.
