### ISSUE TITLE
Svetainė: atspausdinime → atspausdinimas (ne ta raide)

### ISSUE THREAD

**Issue by giedremikutaite** [mokymai/taisymai--BS-2019#37]
1. **Glaustai aprašykite netikslumą:**  ...
2. **Vieta:** 7.2.2 pavyzdys
3. **Nukopijuokite visą sakinį su netikslumu:**  n <- length(vektorius_2) # Apskaičiuojame ir priskiriame
n                        # Atspausdinime
## [1] 4
![fiksavimas](https://user-images.githubusercontent.com/47522731/52560996-bef43b00-2e02-11e9-928a-b30ba9f9dc35.PNG)

 ...
4. **Netikslumo tekstas:**  ...
5. **Siūlomas taisymo tekstas:**  ...
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

**Comment by GegznaV** [comment]
Tas pats kaip #36
