### ISSUE TITLE
Svetainė→ 7.6 ir 7.7 užduotys yra vienodos

### ISSUE THREAD

**Issue by Makauskaite** [mokymai/taisymai--BS-2019#40]
...
3.
![screenshot_1](https://user-images.githubusercontent.com/47527101/52579807-a3535980-2e2f-11e9-844d-0e9f6cbe761d.png)

4. **Netikslumo tekstas:**  ...
5. **Siūlomas taisymo tekstas:**  ...
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

**Comment by GegznaV** [comment]
Vienoje užduotyje prašo pasirinkti, kitoje – pašalinti. Užduotys skirtingos.
