### ISSUE TITLE
Svetainė: raidę→ raide (rašybos klaida)

### ISSUE THREAD

**Issue by gertrudam** [mokymai/taisymai--BS-2019#48]
1. **Glaustai aprašykite netikslumą:**  Rašybos klaida
2. **Vieta:**   7.4 Darbas su kategoriniais kintamaisiais
3. **Nukopijuokite visą sakinį su netikslumu:** 
Paskutinio pavyzdžio kategorijų perkodavimo procedūrą papildykite raidę „C“ perkoduodami į žodį „Citrina“: Rezultatus atvaizduokite grafiškai ir dažnių lentele.
4. **Netikslumo tekstas:**  raidę
5. **Siūlomas taisymo tekstas:**  raide
6. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![klaida8](https://user-images.githubusercontent.com/43219047/52584412-b15aa780-2e3a-11e9-8854-fc0ef5e319fd.PNG)

**Comment by GegznaV** [comment]
Klaidos nematau.
