### ISSUE TITLE
Netinkamai pavartotas žodis "nurodom"

### ISSUE THREAD

**Issue by rasainsodaite** [mokymai/taisymai--BS-2019#5]
1. **Glaustai aprašykite netikslumą:** Netinkamai pavartotas žodis "nurodom"
2. **Vieta**: 2.7 RStudio projektai
3. **Netikslumo tekstas:** nurodom.
4. **Siūlomo taisymo tekstas:** nurodo
5. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![7](https://user-images.githubusercontent.com/43181353/52227164-7515cd00-28b7-11e9-9d97-c7b46352fae0.JPG)

**Comment by GegznaV** [comment]
Vietoje kablelio parašyta "m". Dėkui.
