### ISSUE TITLE
Svetainė: Math Processing error (trūksta tekstinių elementų)

### ISSUE THREAD

**Issue by RPrakapaite** [mokymai/taisymai--BS-2019#66]
1. **Math processing error**  
2. **Skyrius 1.4; Pav. 1.5.** 
3. **Pav. 1.5: R paketo devtools diegimas programiškai. Lange „Console“ [Math Processing Error]
parašomas/įklijuojamas programos kodas [Math Processing Error]
 ir paspaudžiamas klavišas Enter. Atsiranda „STOP“ ženkliukas [Math Processing Error]
, užrašai, rodantys, kad paketai parsiunčiami ir diegiami [Math Processing Error]
 bei atsisiuntimo progreso juosta, kuri iššoka daugybę kartų (čia neparodyta). Sėkmingai įsidiegus paketui, atsiranda apie tai pranešantys užrašai [Math Processing Error]
, išnyksta „STOP“ ikona bei atsiranda „>“ ženkliukas [Math Processing Error]
, rodantis, kad „R“ laukia naujos komandos. Jei paketas nebūtų įdiegtas sėkmingai, „R“ taip pat parašytų priežastį.**

4. **Trūkstami teksto elementai**  
5. **Aiškinamųjų teksto elementų įdėjimas**  
6. 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/45017439/52918993-254af300-3306-11e9-8ca8-ef97521d41b1.png">

**Comment by GegznaV** [comment]
Tai naršyklės problema: arba reikia atnaujinti tinklapį, arba išjungti matematinius simbolius blokuojančius įskiepius, arba prisijungti prie interneto. Įprastai užtenka atnaujinti tinklapį.
