### ISSUE TITLE
Svetainė: operatorių - > operatoriaus 

### ISSUE THREAD

**Issue by UrteJ** [mokymai/taisymai--BS-2019#70]
1. Netinkamas linksnis (vietoj daugiskaitos kilmininko turėtų būti vartojamas vienaskaitos kilmininko linksnis)
2. 7.2.4 Vektoriaus elementų reikšmių pakeitimas, nuoroda: https://mokymai.github.io/biostatistika-2019/r-vektoriai.html
3. Vektoriaus reikšmėms pakeisti naudojama operatorių [] ir <- kombinacija.
4. operatorių
5. operatorius
6. 
![img_20190218_145918](https://user-images.githubusercontent.com/47242129/52952625-ccbf3880-338d-11e9-948c-af4fe9457007.jpg)

**Comment by GegznaV** [comment]
Du operatoriai (`[]` ir `<-`), todėl daugiskaita.
