### ISSUE TITLE
Svetainė: netinkama sakinio struktūra (trūksta kablelio ar jungtuko)

### ISSUE THREAD

**Issue by GretaKont** [mokymai/taisymai--BS-2019#97]
1. Sakinio viduryje trūksta jungtuko ar kablelio.
2. 6.8 Statistinis dažnis ir dažnių lentelės
3. Kintamojo reikšmės dažnis  fi – tai skaičius, nurodantis, kiek kartų reikšmė  xi pasikartojo duomenų eilutėje kinta intervale nuo 0 iki  +∞.
4. pasikartojo duomenų eilutėje kinta intervale
5. pasikartojo duomenų eilutėje bei kinta intervale
[Klaida.pdf](https://github.com/mokymai/taisymai--BS-2019/files/2904225/Klaida.pdf)

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/53397898-fc36fc00-39b0-11e9-9888-4fcd22ceb8f4.png)
